# Site settings
title: Osiris
email: cjkent@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
  Osiris is a library for building and deploying web apps on AWS
baseurl: ""
url: "http://www.osiris.ws" # the base hostname & protocol for your site
twitter_username: cj_kent
github_username:  cjkent

# Build settings
markdown: kramdown
